# Generated by Django 4.2.6 on 2023-10-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='job_title',
        ),
    ]
