# Generated by Django 4.2.6 on 2023-10-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_industry_state_rename_location_job_city_job_job_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
